### ISSUE TITLE
I thought we support selector like "[width ^= \"32\"]"

### ISSUE THREAD

**Issue by rivalnhwc** [siuying/IGHTMLQuery#11]
but when i wrote sth like
`    nodes = [node queryWithCSS:@"[width ^= \"32\"]"];
`
 i got an exception
name:IGXMLQueryCSSConversionException
reason:
Cannot convert CSS into XPath: The operation couldn’t be completed. (CSSSelectorParserErrorDomain error 1.)
callStackSymbols:
0   CoreFoundation                      0x0000000101fc6b0b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x0000000101a2b141 objc_exception_throw + 48
2   CoreFoundation                      0x000000010202f625 +[NSException raise:format:] + 197
3   IGHTMLQuery                         0x00000001011ee150 -[IGXMLDocument queryWithCSS:] + 288

**Comment by siuying** [comment]
Nope. For supported selector, please check https://github.com/siuying/CSSSelectorConverter
