### ISSUE TITLE
Pod dependency

### ISSUE THREAD

**Issue by serluca** [siuying/IGHTMLQuery#7]
Importing the library through cocoapods the pod import wrong libraries, some required are not there and some not required are there. 

This is a list that I receive using pod update
```
Using CSSSelectorConverter (1.2.1) 
Using CocoaLumberjack (1.9.2)
Using IGHTMLQuery (0.8.4)
Using NUIParse (1.2.1)
```

This is the list that I expect to have
```
Using IGHTMLQuery (0.8.4)
Using CSSSelectorConverter (1.2.1) 
Using JavaScriptCoreOpalAdditions (0.3.1)
```

I looked into the code and I'm pretty sure that the error is in the podspec and into the podfile.lock

**Comment by kaandedeoglu** [comment]
@serluca take a look at the podspec for `CSSSelectorConverter`, it depends on both `CocoaLumberjack` and `NUIParse`, so `IGHTMQuery` also inherits those dependencies.

**Comment by siuying** [comment]
Like @kaandedeoglu said, ``NUIParse`` is a dependency of CSSSelectorConverter, and  ``JavaScriptCoreOpalAdditions`` is only needed if you imported ``IGHTMLQuery/Ruby`` sub-spec. Cocoapods is a dependency manager, it do not only add what you specify, but also their dependency.
