### ISSUE TITLE
Compile error in Swift project

### ISSUE THREAD

**Issue by twiedow** [siuying/IGHTMLQuery#9]
I want to use IGHTMLQuery via Cocoapods in my Swift project. I already integrated in another Swift project with iOS 7 and no frameworks. Now I want to use iOS 8 and frameworks, but then I get a compile error:

<FOLDER>/Pods/IGHTMLQuery/IGHTMLQuery/Classes/IGHTMLDocument.h:9:9: Include of non-modular header inside framework module 'IGHTMLQuery.IGHTMLDocument'

in this line

#import <libxml2/libxml/HTMLparser.h>

This is my pod file:

platform :ios, '8.0'
use_frameworks!

pod 'IGHTMLQuery', '~> 0.8.0'

Do you know how to fix it?

**Comment by siuying** [comment]
I have push a new version '0.9.0', which should fix the issue. Please check it out and see if it solve the problem.

**Comment by siuying** [comment]
Please reopen the issue if 0.9.0 did not resolve the problem.
